---
version: "3.8"
services:
  api:
    image: redalegzali/restapi
    build: restapi/
    container_name: movie_api
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    restart: always
    depends_on:
      - database
    ports:
      - "8000:8000"
    environment:
      - HOST=database
      - PORT=3306
      - DATABASE=${db}
      - DBUSER=${dbuser}
      - PASSWORD=${dbpass}
    networks:
      - backend
    volumes:
      - images:/app/img
  web:
    image: redalegzali/webapp
    build: webapp/
    container_name: movie_app
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
  database:
    image: mariadb
    restart: always
    container_name: movie_db
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${dbroot}
      - MYSQL_DATABASE=${db}
      - MYSQL_USER=${dbuser}
      - MYSQL_PASSWORD=${dbpass}
    ports:
      - "3306"
    networks:
      - backend
    volumes:
      - data:/var/lib/mysql

networks:
  backend:
    driver: overlay

volumes:
  data:
    driver: nfs
    driver_opts:
      share: 192.168.33.10:/mysql
  images:
    driver: nfs
    driver_opts:
      share: 192.168.33.10:/mysql

