
---
version: "3.9"
services:
  flaskapi:
    build: ./restful-api
    container_name: flaskapi
    restart: always
    depends_on:
      - "mariadb"
    ports:
      - "8000:8000"
    environment:
      - HOST=mariadb
      - PORT=3306
      - DATABASE=movieapp
      - USER=myuser
      - PASSWORD=password123
    networks:
      - net
    volumes:
      - images:/app/img/
  reactapp:
    build: ./web-app
    container_name: webapp
    restart: always
    ports:
      - "5000:5000"
    networks:
      - net
  mariadb:
    image: "mariadb:latest"
    restart: always
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword123
      - MYSQL_DATABASE=movieapp
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=password123
    ports:
      - "3306"
    networks:
      - net
    volumes:
      - data:/var/lib/mysql/movieapp

networks:
  net:
    driver: bridge

volumes:
  data:
    driver: local
  images:
    driver: local
