
---
version: "3.9"
services:
  flaskapi:
    image: "restfulapi:latest"
    build: restful-api/
    container_name: flaskapi
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8000:8000"
    environment:
      - HOST=mariadb
      - PORT=3306
      - DATABASE=${db}
      - DBUSER=${dbuser}
      - PASSWORD=${dbpass}
    networks:
      - backend
    volumes:
      - images:/app/img
  reactapp:
    image: "webapp:latest"
    build: web-app/
    container_name: webapp
    ports:
      - "5000:5000"
  mariadb:
    image: "mariadb:latest"
    restart: always
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${dbroot}
      - MYSQL_DATABASE=${db}
      - MYSQL_USER=${dbuser}
      - MYSQL_PASSWORD=${dbpass}
    ports:
      - "3306"
    networks:
      - backend
    volumes:
      - data:/var/lib/mysql

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
  images:
    driver: local
