---
version: "3.9"
services:
  api:
    image: "restfulapi:latest"
    build: restful-api/
    container_name: movie_api
    restart: always
    depends_on:
      - database
    ports:
      - "8000:8000"
    environment:
      - HOST=database
      - PORT=3306
      - DATABASE=${db}
      - DBUSER=${dbuser}
      - PASSWORD=${dbpass}
    networks:
      - backend
    volumes:
      - images:/app/img
  web:
    image: "webapp:latest"
    build: web-app/
    container_name: movie_app
    ports:
      - "80:80"
  database:
    image: "mariadb:latest"
    restart: always
    container_name: movie_db
    environment:
      - MYSQL_ROOT_PASSWORD=${dbroot}
      - MYSQL_DATABASE=${db}
      - MYSQL_USER=${dbuser}
      - MYSQL_PASSWORD=${dbpass}
    ports:
      - "3306"
    networks:
      - backend
    volumes:
      - data:/var/lib/mysql

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
  images:
    driver: local

